import type { ReportResponse } from "./types/report";

export const MOCK_REPORT: ReportResponse = {
  tool_version: "0.1.0",
  generated_at: "2025-08-18T12:00:00Z",
  profile: {
    username: "testuser",
    analyzed_at: "2025-08-18T12:00:00Z",
    schema_version: 1,
    analyses: {
      presence: null,
      readme: null,
      repository_quality: null,
      repository_activity: null,
      portfolio: null,
      stars: null,
      star_growth: null,
      network: null,
      commits: null,
      contribution_calendar: null,
      pull_requests: null,
      issues: null,
      languages: {
        distribution: [
          { language: "TypeScript", bytes: 50000, share: 0.45 },
          { language: "Python", bytes: 30000, share: 0.27 },
          { language: "Go", bytes: 20000, share: 0.18 },
          { language: "Shell", bytes: 11000, share: 0.1 },
        ],
        dominant_language: "TypeScript",
        dominant_share: 0.45,
        distinct_languages: 4,
        total_bytes: 111000,
        metrics: [],
        findings: [],
      },
      technology: null,
    },
    metrics: [],
    scores: [
      {
        dimension: "presence",
        score: 65,
        weight: 0.15,
        rationale: "Good profile presence.",
        breakdown: [
          { component_id: "has_avatar", label: "Has avatar", weight: 0.5, contribution: 40, metric_id: null, sources: [] },
          { component_id: "has_bio", label: "Has bio", weight: 0.5, contribution: 25, metric_id: null, sources: [] },
        ],
      },
      {
        dimension: "code_quality",
        score: 80,
        weight: 0.15,
        rationale: "High quality code.",
        breakdown: [
          { component_id: "readme_score", label: "README", weight: 0.4, contribution: 32, metric_id: null, sources: [] },
          { component_id: "repo_quality", label: "Repo quality", weight: 0.6, contribution: 48, metric_id: null, sources: [] },
        ],
      },
      {
        dimension: "activity",
        score: 70,
        weight: 0.1,
        rationale: "Moderate activity.",
        breakdown: [],
      },
      {
        dimension: "engagement",
        score: 55,
        weight: 0.1,
        rationale: "Could improve engagement.",
        breakdown: [],
      },
      {
        dimension: "documentation",
        score: 75,
        weight: 0.1,
        rationale: "Well documented.",
        breakdown: [],
      },
      {
        dimension: "open_source",
        score: 60,
        weight: 0.1,
        rationale: "Some open source work.",
        breakdown: [],
      },
      {
        dimension: "consistency",
        score: 50,
        weight: 0.1,
        rationale: "Inconsistent activity.",
        breakdown: [],
      },
      {
        dimension: "contribution",
        score: 85,
        weight: 0.1,
        rationale: "Strong contributor.",
        breakdown: [],
      },
      {
        dimension: "visibility",
        score: 45,
        weight: 0.1,
        rationale: "Low visibility.",
        breakdown: [],
      },
    ],
    overall: {
      overall: 65,
      contributions: [
        { dimension: "code_quality", score: 80, weight: 0.15, contribution: 12 },
        { dimension: "contribution", score: 85, weight: 0.1, contribution: 8.5 },
      ],
      strengths: ["Strong code quality", "Active contributor"],
      weaknesses: ["Low visibility", "Inconsistent activity"],
    },
    findings: [
      {
        id: "f1",
        type: "missing_readme",
        severity: "high",
        title: "Missing README in main repo",
        message: "The primary repository lacks a README file.",
        dimension: "documentation",
        evidence: [],
        recommendation_ids: ["r1"],
      },
      {
        id: "f2",
        type: "low_activity",
        severity: "medium",
        title: "Low commit frequency",
        message: "Only 3 commits in the last 30 days.",
        dimension: "activity",
        evidence: [],
        recommendation_ids: ["r2"],
      },
      {
        id: "f3",
        type: "no_avatar",
        severity: "low",
        title: "Default avatar",
        message: "Profile still uses the default GitHub avatar.",
        dimension: "presence",
        evidence: [],
        recommendation_ids: [],
      },
    ],
    recommendations: [
      {
        id: "r1",
        priority: "high",
        action: "Add a README to your main repository",
        rationale: "A README helps visitors understand your project.",
        template_id: "add_readme",
        severity: "high",
        effort: "low",
        finding_ids: ["f1"],
        metric_ids: [],
        sources: [],
      },
      {
        id: "r2",
        priority: "medium",
        action: "Commit more regularly",
        rationale: "Regular commits show active maintenance.",
        template_id: "regular_commits",
        severity: "medium",
        effort: "medium",
        finding_ids: ["f2"],
        metric_ids: [],
        sources: [],
      },
    ],
    synthesis: null,
  },
};
