import type { ReportResponse } from "./types/report";

export const MOCK_REPORT: ReportResponse = {
  tool_version: "0.1.0",
  generated_at: "2025-08-18T12:00:00Z",
  profile: {
    username: "testuser",
    analyzed_at: "2025-08-18T12:00:00Z",
    schema_version: 1,
    identity: {
      username: "testuser",
      name: "Test User",
      avatar_url: null,
      html_url: "https://github.com/testuser",
      bio: "Building developer tools in the open.",
      company: "Acme",
      blog: "https://testuser.dev",
      location: "San Francisco",
      email: "test@example.com",
      twitter_username: "testuser",
      hireable: true,
      public_repos: 12,
      public_gists: 3,
      followers: 1200,
      following: 80,
      created_at: "2015-01-10T00:00:00Z",
      updated_at: "2025-08-01T00:00:00Z",
      availability: "available",
    },
    top_stats: {
      username: "testuser",
      metrics: [
        { id: "top_stats.repositories", label: "Public repositories", value: 12, sources: [], timestamp: "2025-08-18T12:00:00Z", confidence: 1, availability: "available" },
        { id: "top_stats.stars", label: "Total stars", value: 1530, sources: [], timestamp: "2025-08-18T12:00:00Z", confidence: 1, availability: "available" },
        { id: "top_stats.forks", label: "Total forks", value: 210, sources: [], timestamp: "2025-08-18T12:00:00Z", confidence: 1, availability: "available" },
        { id: "top_stats.followers", label: "Followers", value: 1200, sources: [], timestamp: "2025-08-18T12:00:00Z", confidence: 1, availability: "available" },
        { id: "top_stats.following", label: "Following", value: 80, sources: [], timestamp: "2025-08-18T12:00:00Z", confidence: 1, availability: "available" },
        { id: "top_stats.commits", label: "Commits collected", value: 420, sources: [], timestamp: "2025-08-18T12:00:00Z", confidence: 1, availability: "partial" },
        { id: "top_stats.contributions", label: "Contributions (past year)", value: 1280, sources: [], timestamp: "2025-08-18T12:00:00Z", confidence: 1, availability: "partial" },
      ],
      top_repositories: [
        { name: "toolkit", full_name: "testuser/toolkit", stargazers_count: 1000, description: "A developer toolkit", html_url: "https://github.com/testuser/toolkit", language: "TypeScript" },
        { name: "resume", full_name: "testuser/resume", stargazers_count: 530, description: null, html_url: "https://github.com/testuser/resume", language: null },
      ],
      top_languages: [
        { language: "TypeScript", bytes: 50000, share: 0.45 },
        { language: "Python", bytes: 30000, share: 0.27 },
        { language: "Go", bytes: 20000, share: 0.18 },
        { language: "Shell", bytes: 11000, share: 0.1 },
      ],
      sources: [{ entity: "profile", identifier: "testuser", field: null }],
      availability: "available",
    },
    analyses: {
      presence: null,
      readme: {
        username: "testuser",
        status: "present",
        metrics: [
          { id: "readme.present", label: "Profile README present", value: true, timestamp: "2025-08-18T12:00:00Z", sources: [], confidence: 1, availability: "available" },
          { id: "readme.word_count", label: "README word count", value: 42, timestamp: "2025-08-18T12:00:00Z", sources: [], confidence: 1, availability: "available" },
        ],
        findings: [],
        content:
          "# Hi there\n\nI build **developer tools** in the open.\n\n## Links\n\n- [Website](https://testuser.dev)\n\n```ts\nconst ok = true;\n```",
        repository: "testuser/testuser",
      },
      repository_quality: null,
      repository_activity: null,
      portfolio: null,
      stars: null,
      star_growth: null,
      network: null,
      commits: null,
      contribution_calendar: null,
      pull_requests: null,
      issues: null,
      languages: {
        distribution: [
          { language: "TypeScript", bytes: 50000, share: 0.45 },
          { language: "Python", bytes: 30000, share: 0.27 },
          { language: "Go", bytes: 20000, share: 0.18 },
          { language: "Shell", bytes: 11000, share: 0.1 },
        ],
        dominant_language: "TypeScript",
        dominant_share: 0.45,
        distinct_languages: 4,
        total_bytes: 111000,
        metrics: [],
        findings: [],
      },
      technology: null,
    },
    metrics: [],
    scores: [
      {
        dimension: "presence",
        score: 65,
        weight: 0.15,
        rationale: "Good profile presence.",
        breakdown: [
          { component_id: "has_avatar", label: "Has avatar", weight: 0.5, contribution: 40, metric_id: null, sources: [] },
          { component_id: "has_bio", label: "Has bio", weight: 0.5, contribution: 25, metric_id: null, sources: [] },
        ],
      },
      {
        dimension: "code_quality",
        score: 80,
        weight: 0.15,
        rationale: "High quality code.",
        breakdown: [
          { component_id: "readme_score", label: "README", weight: 0.4, contribution: 32, metric_id: null, sources: [] },
          { component_id: "repo_quality", label: "Repo quality", weight: 0.6, contribution: 48, metric_id: null, sources: [] },
        ],
      },
      {
        dimension: "activity",
        score: 70,
        weight: 0.1,
        rationale: "Moderate activity.",
        breakdown: [],
      },
      {
        dimension: "engagement",
        score: 55,
        weight: 0.1,
        rationale: "Could improve engagement.",
        breakdown: [],
      },
      {
        dimension: "documentation",
        score: 75,
        weight: 0.1,
        rationale: "Well documented.",
        breakdown: [],
      },
      {
        dimension: "open_source",
        score: 60,
        weight: 0.1,
        rationale: "Some open source work.",
        breakdown: [],
      },
      {
        dimension: "consistency",
        score: 50,
        weight: 0.1,
        rationale: "Inconsistent activity.",
        breakdown: [],
      },
      {
        dimension: "contribution",
        score: 85,
        weight: 0.1,
        rationale: "Strong contributor.",
        breakdown: [],
      },
      {
        dimension: "visibility",
        score: 45,
        weight: 0.1,
        rationale: "Low visibility.",
        breakdown: [],
      },
    ],
    overall: {
      overall: 65,
      contributions: [
        { dimension: "code_quality", score: 80, weight: 0.15, contribution: 12 },
        { dimension: "contribution", score: 85, weight: 0.1, contribution: 8.5 },
      ],
      strengths: ["Strong code quality", "Active contributor"],
      weaknesses: ["Low visibility", "Inconsistent activity"],
    },
    findings: [
      {
        id: "f1",
        type: "missing_readme",
        severity: "high",
        title: "Missing README in main repo",
        message: "The primary repository lacks a README file.",
        dimension: "documentation",
        evidence: [],
        recommendation_ids: ["r1"],
      },
      {
        id: "f2",
        type: "low_activity",
        severity: "medium",
        title: "Low commit frequency",
        message: "Only 3 commits in the last 30 days.",
        dimension: "activity",
        evidence: [],
        recommendation_ids: ["r2"],
      },
      {
        id: "f3",
        type: "no_avatar",
        severity: "low",
        title: "Default avatar",
        message: "Profile still uses the default GitHub avatar.",
        dimension: "presence",
        evidence: [],
        recommendation_ids: [],
      },
    ],
    recommendations: [
      {
        id: "r1",
        priority: "high",
        action: "Add a README to your main repository",
        rationale: "A README helps visitors understand your project.",
        template_id: "add_readme",
        severity: "high",
        effort: "low",
        finding_ids: ["f1"],
        metric_ids: [],
        sources: [],
      },
      {
        id: "r2",
        priority: "medium",
        action: "Commit more regularly",
        rationale: "Regular commits show active maintenance.",
        template_id: "regular_commits",
        severity: "medium",
        effort: "medium",
        finding_ids: ["f2"],
        metric_ids: [],
        sources: [],
      },
    ],
    synthesis: null,
  },
};
