"""Recorded-response replay for tests (issues #59 and #61).

Loads the versioned sessions generated by :mod:`tests.fixtures.generate_corpus`
and serves them through an ``httpx.BaseTransport``, so the full collection
pipeline runs against recorded responses without ever touching the live API.

Strict mode (the default) raises :class:`UnrecordedRequestError` for any
request that is not present in the session. Tests therefore fail loudly if the
pipeline starts making requests the corpus was not designed for — the corpus
is a contract, not a loose stub.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import httpx

from ghdtk.api.client import GITHUB_API_URL, GitHubClient
from ghdtk.api.rate_limit import BackoffPolicy

CORPUS_DIR = Path(__file__).parent / "corpus"
CORPUS_VERSION = 1


class SessionVersionError(RuntimeError):
    """Raised when a session's version does not match the replay format."""


class UnrecordedRequestError(RuntimeError):
    """Raised when a request is not covered by the recorded session."""


def _params_key(params: dict[str, str] | None) -> tuple[tuple[str, str], ...]:
    return tuple(sorted((params or {}).items()))


def _request_key(request: httpx.Request) -> tuple[str, str, tuple[tuple[str, str], ...]]:
    query = tuple(sorted((key, value) for key, value in request.url.params.items()))
    return (request.method.upper(), request.url.path, query)


class ReplayTransport(httpx.BaseTransport):
    """An ``httpx`` transport that serves recorded responses from a session."""

    def __init__(self, session: dict[str, Any], *, strict: bool = True) -> None:
        version = session.get("version")
        if version != CORPUS_VERSION:
            raise SessionVersionError(
                f"Unsupported session version {version!r}; expected {CORPUS_VERSION}"
            )
        entries = session.get("requests")
        if not isinstance(entries, list):
            raise ValueError("Session has no 'requests' list")
        self._entries: dict[tuple[str, str, tuple[tuple[str, str], ...]], dict[str, Any]] = {}
        for entry in entries:
            key = (
                str(entry["method"]).upper(),
                str(entry["path"]),
                _params_key(entry.get("params")),
            )
            if key in self._entries:
                raise ValueError(f"Duplicate recorded entry for {key}")
            self._entries[key] = entry
        self._strict = strict

    def handle_request(self, request: httpx.Request) -> httpx.Response:
        entry = self._entries.get(_request_key(request))
        if entry is None:
            if not self._strict:
                return httpx.Response(404, json={"message": "Not Found"}, request=request)
            raise UnrecordedRequestError(f"No recorded response for {request.method} {request.url}")
        return _build_response(request, entry)


def _build_response(request: httpx.Request, entry: dict[str, Any]) -> httpx.Response:
    response = entry["response"]
    status = int(response["status"])
    headers = response.get("headers") or {}
    if "content" in response:
        content = response["content"]
        raw = content.encode("utf-8") if isinstance(content, str) else bytes(content)
        return httpx.Response(status, content=raw, headers=headers, request=request)
    return httpx.Response(status, json=response.get("body"), headers=headers, request=request)


def load_session(profile_id: str) -> dict[str, Any]:
    """Load and validate a recorded session by its profile id."""
    path = CORPUS_DIR / f"{profile_id}/session.json"
    if not path.exists():
        raise FileNotFoundError(f"No recorded session for {profile_id!r}: {path}")
    with path.open(encoding="utf-8") as handle:
        session: dict[str, Any] = json.load(handle)
    if session.get("version") != CORPUS_VERSION:
        raise SessionVersionError(
            f"Session {profile_id} has version {session.get('version')!r}, "
            f"expected {CORPUS_VERSION}"
        )
    return session


def list_profiles() -> list[str]:
    """Return the ids of every full (non-error) profile in the corpus."""
    return [
        entry["id"]
        for entry in json.loads((CORPUS_DIR / "MANIFEST.json").read_text(encoding="utf-8"))[
            "profiles"
        ]
        if "/" not in entry["id"]
    ]


def client_from_session(
    session: dict[str, Any],
    *,
    base_url: str = GITHUB_API_URL,
    per_page: int = 100,
    max_retries: int = 1,
) -> GitHubClient:
    """Build a client that replays the given session."""
    backoff = BackoffPolicy(
        base_delay=0.0,
        max_delay=0.0,
        sleep_fn=lambda seconds: None,
        random_fn=lambda low, high: 0.0,
    )
    return GitHubClient(
        "test-token",
        base_url=base_url,
        transport=ReplayTransport(session),
        per_page=per_page,
        max_retries=max_retries,
        backoff=backoff,
    )


__all__ = [
    "CORPUS_DIR",
    "CORPUS_VERSION",
    "ReplayTransport",
    "SessionVersionError",
    "UnrecordedRequestError",
    "client_from_session",
    "list_profiles",
    "load_session",
]
